### ISSUE TITLE
Control not rendering in CLI

### ISSUE THREAD

**Issue by emreertugrul** [TGMorais/aurelia-tags-input#1]
Hi, I'm trying to use this component with Aurelia and it doesn't render the control. I'm guessing it's not loading the html/css. I've tried many combinations in the dependency registration in Aurelia.json, and none of it worked. Could you please provide the dependency signature? Or what else could be going wrong? I'm using cli and this is the registration I currently use:

`          {
            "name": "aurelia-tags-input",
            "path": "../node_modules/aurelia-tags-input/dist/amd",
            "main": "aurelia-tags-input",
            "resources": [
              "**/*.{css,html}"
            ]
          }`

**Comment by tiagogm** [comment]
This should do the trick
https://github.com/TGMorais/aurelia-tags-input#using-aurelia-cli
http://aurelia.io/docs/build-systems/aurelia-cli#adding-client-libraries-to-your-project
